version: "3.6"

services:

  fhir_db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "hapi"
      POSTGRES_PASSWORD: "hapi"
      POSTGRES_DB: "hapi_r5"


  fhir-server:
    image: trifork/gravitate
    ports:
      - "8080:8080"
    depends_on:
      - fhir_db
    environment:
      - SPRING_CONFIG_LOCATION=https://raw.githubusercontent.com/trifork/hapi-fhir-jpaserver-starter/gravitate/src/main/resources/application.yaml
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fhir_db:5432/hapi_r5
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=hapi
      - SPRING_DATASOURCE_PASSWORD=hapi
